# Site settings
title: 플랫폼이 콘텐츠다
email: canshot@business.kaist.edu
url: https://canshot.github.io/sss3
description: "이 책은 digital technology가 </br>영화, 음반, 출판 등 엔터테인먼트 산업에<br>어떤 perfect storm을 몰고 왔는지에 대한 이야기다" 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'linear-gradient (#05FBFF , #1E00FF)'
  links: '#219ab3'

# Footer settings
footer: Jaewan Lim 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 
    url: 
  - title: facebook
    url:
  - title: 
    url: 
  - title: 
    url: 
  - title: 
    url: 

# Build settings
markdown: kramdown
permalink: pretty
